
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Daryl Branford
 */
public class CashierWindow extends javax.swing.JFrame {
     private static final String username = "root";
  private static final String password = "root";
  private static final String data_con = "jdbc:mysql://localhost:3306/ZeroHardware";
    PreparedStatement s = null;
        Statement st = null;
        Statement st_Sales = null;
        ResultSet r_set = null;
        float Price = 0;
        LocalDate Final_Date = LocalDate.now();
        long currentSaleId = -1;
        
        
    /**
     * Creates new form CashierWindow
     */
    public CashierWindow() {
        initComponents();
        setDefaultCloseOperation(CashierWindow.DISPOSE_ON_CLOSE);
        Item_Info();
        Date_Sold_Field.setText("" + Final_Date);
        
        // create new sale
        try{
                    
            Connection connect= DriverManager.getConnection(data_con, username, password);
            PreparedStatement st = connect.prepareStatement("insert into Customer_Sale(Date_sold_handler) values(now());", Statement.RETURN_GENERATED_KEYS);
            int affectedRows  = st.executeUpdate();
            ResultSet resultKeys = st.getGeneratedKeys();
            resultKeys.next();// todo: check for error
            currentSaleId = resultKeys.getLong(1);// get last inserted id
            
            connect.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    Connection connect = null;
    
        public void Item_Info(){
        try{
            connect= DriverManager.getConnection(data_con, username, password);
            st = connect.createStatement();
            r_set= st.executeQuery("select * from Item_Information;");
            Item_Information.setModel(DbUtils.resultSetToTableModel(r_set));
        }catch(Exception e){
            e.printStackTrace();
        }
    }
        
    public void Sale_Info(){
        try{
            connect= DriverManager.getConnection(data_con, username, password);
            st_Sales = connect.createStatement();
            r_set= st.executeQuery("select * from Sales_Information where Customer_Sale_ID="+currentSaleId+";");
            Sales_Display_Table.setModel(DbUtils.resultSetToTableModel(r_set));
        }catch(Exception e){
            e.printStackTrace();
        }
    }
        
//    public void Item_Info(){
//        try{
//            connect= DriverManager.getConnection(data_con, username, password);
//            s = connect.prepareStatement("select Sale_Price from Item_Information where Item_ID =" + "'"+Item_ID_Field.getText()+"'");
//            r_set= s.executeQuery();
//            //Item_Information.setModel(DbUtils.resultSetToTableModel(r_set));
//            while(r_set.next()) {
//                System.out.println("Sale_Price");
//                 
//            }
//        }catch(Exception e){
//            e.printStackTrace();
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Modify_Item = new javax.swing.JButton();
        Produce_Reports = new javax.swing.JButton();
        Reset_Password = new javax.swing.JButton();
        Add_New_Item_Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Item_Information = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Quantity_Label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Item_ID_Field = new javax.swing.JTextField();
        Item_Description_Field = new javax.swing.JTextField();
        Total_In_Stock_Field = new javax.swing.JTextField();
        Understock_Value_Field = new javax.swing.JTextField();
        Sale_Price_Field = new javax.swing.JTextField();
        Purchase_Price_Field = new javax.swing.JTextField();
        Quantity_Field = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Sales_Display_Table = new javax.swing.JTable();
        Customer_Name_Field = new javax.swing.JTextField();
        Date_Sold_Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        Modify_Item.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Modify_Item.setText("Price Check");
        Modify_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Modify_ItemMouseClicked(evt);
            }
        });
        Modify_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modify_ItemActionPerformed(evt);
            }
        });

        Produce_Reports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Produce_Reports.setText("Print Reciept");
        Produce_Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produce_ReportsActionPerformed(evt);
            }
        });

        Reset_Password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Reset_Password.setText("Reset Password");
        Reset_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_PasswordActionPerformed(evt);
            }
        });

        Add_New_Item_Button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Add_New_Item_Button.setText("Add New Item");
        Add_New_Item_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_Item_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Modify_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Produce_Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add_New_Item_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reset_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Add_New_Item_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(Modify_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(Produce_Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(Reset_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("Cashier's Menu");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Item_Information.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Item Id", "Item Description", "Total in Stock", "Understock Value", "Sale Price", "Purchase Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Item_Information.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_InformationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Item_Information);

        jLabel1.setText("Item ID");

        jLabel2.setText("Item Description");

        jLabel3.setText("Total in Stock");

        jLabel4.setText("Understock Value");

        jLabel5.setText("Sale Price");

        jLabel6.setText("Purchase Price");

        Quantity_Label.setText("Quantity");

        jLabel8.setText("Customer Name");

        jLabel9.setText("Date Sold");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Quantity_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        Purchase_Price_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_Price_FieldActionPerformed(evt);
            }
        });

        Sales_Display_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Item ID", "Quantity Sold", "Date Sold", "Sale Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Sales_Display_Table);

        Date_Sold_Field.setEditable(false);
        Date_Sold_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_Sold_FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Date_Sold_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(Customer_Name_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(Item_ID_Field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item_Description_Field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Total_In_Stock_Field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Understock_Value_Field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sale_Price_Field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Purchase_Price_Field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quantity_Field, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Item_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Item_Description_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Total_In_Stock_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Understock_Value_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Sale_Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Purchase_Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Quantity_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Customer_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Date_Sold_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Zero's Hardware");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jSeparator2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Purchase_Price_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_Price_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Purchase_Price_FieldActionPerformed

    private void Modify_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modify_ItemActionPerformed
        // TODO add your handling code here:
            try{
            connect= DriverManager.getConnection(data_con, username, password);
            int item = Integer.valueOf(Item_ID_Field.getText());
            s = connect.prepareStatement("select * from Item_Information where Item_ID = "+ item);
            r_set= s.executeQuery();

            while(r_set.next()) {
                System.out.println(r_set.getFloat("Sale_Price"));
                JOptionPane.showMessageDialog(this,"The price for Item " + item + " is $" + r_set.getFloat("Sale_Price"));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_Modify_ItemActionPerformed

    private void Modify_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modify_ItemMouseClicked
        // TODO add your handling code here:
//        try{
//            connect = DriverManager.getConnection(data_con, username, password);
//            
//            String PriceCheck ="Select Sale_Price from Item_Information where Item_ID = '"+ Item_ID_Field.getText();
//            statement =connect.createStatement();
//            statement.executeUpdate(PriceCheck);
//                 
//        } catch (SQLException ex) {
//            Logger.getLogger(ManagerWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            try{
//            connect= DriverManager.getConnection(data_con, username, password);
//            int item = Integer.parseInt(Item_ID_Field.getText());
//            s = connect.prepareStatement("select Sale_Price from Item_Information where Item_ID =?");
//            s.setInt(1, item);
//            r_set= s.executeQuery();
//            System.out.println(Price);
//            //Item_Information.setModel(DbUtils.resultSetToTableModel(r_set));
//            while(r_set.next()) {
//                Price = r_set.getFloat("Sale_Price");
//                System.out.println(Price);
//            }
//        }catch(Exception e){
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_Modify_ItemMouseClicked

    private void Item_InformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_InformationMouseClicked

       DefaultTableModel model = (DefaultTableModel) Item_Information.getModel();
       int Myindex = Item_Information.getSelectedRow();
        try {
            getData(connect, "");
            Item_ID_Field.setText(model.getValueAt(Myindex, 0).toString());
            Item_Description_Field.setText(model.getValueAt(Myindex, 1).toString());
            Total_In_Stock_Field.setText(model.getValueAt(Myindex, 2).toString());
            Understock_Value_Field.setText(model.getValueAt(Myindex, 3).toString());
            Sale_Price_Field.setText(model.getValueAt(Myindex, 4).toString());
            Purchase_Price_Field.setText(model.getValueAt(Myindex, 5).toString());
            
        } catch (SQLException ex) {
            Logger.getLogger(ManagerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }                                              
    }//GEN-LAST:event_Item_InformationMouseClicked

    private void Add_New_Item_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_Item_ButtonActionPerformed
        // TODO add your handling code here:
         try {
                    connect = DriverManager.getConnection(data_con, username, password);
                    PreparedStatement in = connect.prepareStatement("insert into Sales_Information (Customer_Name, Item_ID, Quantity_Sold, Date_Sold, Sale_Price, Customer_Sale_ID)values(?,?,?,?,?,?);");
                    in.setString(1, String.valueOf(Customer_Name_Field.getText()));
                    in.setInt(2, Integer.parseInt(Item_ID_Field.getText()));
                    in.setInt(3, Integer.valueOf(Quantity_Field.getText()));
                    in.setString(4, (Date_Sold_Field.getText()));
                    in.setFloat(5, Float.valueOf(Sale_Price_Field.getText()));
                    in.setLong(6, currentSaleId);
                    in.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Item Added Successfully");
                    Item_Info();
                    
                    
                }
                catch (Exception e){
                    e.printStackTrace();
                }
         Sale_Info();
    
    }//GEN-LAST:event_Add_New_Item_ButtonActionPerformed

    private void Produce_ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produce_ReportsActionPerformed
        // TODO add your handling code here:
        new SalesReceipt(currentSaleId).setVisible(true);
    }//GEN-LAST:event_Produce_ReportsActionPerformed

    private void Date_Sold_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_Sold_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_Sold_FieldActionPerformed

    private void Reset_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_PasswordActionPerformed
        // TODO add your handling code here:
        new ResetPasswordCashier().setVisible(true);
    }//GEN-LAST:event_Reset_PasswordActionPerformed


    private ResultSet getData(Connection conn, String x ) throws SQLException{
        ResultSet x1 = null;
        String x2 = x;
        String result = "abc";
        PreparedStatement get = conn.prepareStatement("select Item_ID from Item_Information where Item_ID = ?;");
        get.setString(1, x2);
        x1 = get.executeQuery();
        return x1;
       
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Item_Button;
    private javax.swing.JTextField Customer_Name_Field;
    private javax.swing.JTextField Date_Sold_Field;
    private javax.swing.JTextField Item_Description_Field;
    private javax.swing.JTextField Item_ID_Field;
    private javax.swing.JTable Item_Information;
    private javax.swing.JButton Modify_Item;
    private javax.swing.JButton Produce_Reports;
    private javax.swing.JTextField Purchase_Price_Field;
    private javax.swing.JTextField Quantity_Field;
    private javax.swing.JLabel Quantity_Label;
    private javax.swing.JButton Reset_Password;
    private javax.swing.JTextField Sale_Price_Field;
    private javax.swing.JTable Sales_Display_Table;
    private javax.swing.JTextField Total_In_Stock_Field;
    private javax.swing.JTextField Understock_Value_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
