import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Daryl Branford
 */
public class ManagerReports extends javax.swing.JFrame {
    private static final String username = "root";
  private static final String password = "root";
  private static final String data_con = "jdbc:mysql://localhost:3306/ZeroHardware";

PreparedStatement s = null;
        Statement st = null;
        Statement st_Sales = null;
        ResultSet r_set = null;
        float Price = 0;
        Calendar calendar = Calendar.getInstance();
        java.util.Date Date_S = new java.util.Date();
        String S_D_F = ("dd-mm-yyyy");
//        SimpleDateFormat Sim_Format= new SimpleDateFormat(S_D_F);
        String Final_Date = DateFormat.getInstance().format(Date_S);
        
    /**
     * Creates new form ManagerScreen
     */
    public ManagerReports() {
        initComponents();
        setDefaultCloseOperation(ManagerReports.DISPOSE_ON_CLOSE);
//        Item_Info();
    }
    
    Connection connect = null;
        Statement statement = null;
//        
//    public void Item_Info(){
//        try{
//            connect= DriverManager.getConnection(data_con, username, password);
//            statement= connect.createStatement();
//            r_set= statement.executeQuery("select * from Item_Information;");
//            QTY_Report_Display.setModel(DbUtils.resultSetToTableModel(r_set));
//        }catch(Exception e){
//            e.printStackTrace();
//        }
//    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Daily_QTY_Report = new javax.swing.JButton();
        Total_Sales_Month_End = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        QTY_Report_Display = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Total_Sales_Month_Display = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        Daily_QTY_Report.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Daily_QTY_Report.setText("Daily Quantity Report");
        Daily_QTY_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Daily_QTY_ReportMouseClicked(evt);
            }
        });
        Daily_QTY_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Daily_QTY_ReportActionPerformed(evt);
            }
        });

        Total_Sales_Month_End.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Total_Sales_Month_End.setText("Total Sales at Month End");
        Total_Sales_Month_End.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Total_Sales_Month_EndMouseClicked(evt);
            }
        });
        Total_Sales_Month_End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_Sales_Month_EndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Daily_QTY_Report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Total_Sales_Month_End, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(Daily_QTY_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(Total_Sales_Month_End, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("Daily Quantity report");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        QTY_Report_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item Id", "Item Description", "Total in Stock", "Understock Value", "Sale Price", "Purchase Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        QTY_Report_Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QTY_Report_DisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(QTY_Report_Display);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel8.setBackground(new java.awt.Color(204, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Zero's Hardware ");

        Total_Sales_Month_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sales Id", "Customer Name", "Item ID", "Understock Value", "Date Sold"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Total_Sales_Month_Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Total_Sales_Month_DisplayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Total_Sales_Month_Display);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setText("Total Sales at Month End");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QTY_Report_DisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTY_Report_DisplayMouseClicked
        // TODO add your handling code here:

//        DefaultTableModel model = (DefaultTableModel) QTY_Report_Display.getModel();
//        int Myindex = QTY_Report_Display.getSelectedRow();
//        try {
//            getData(connect, "");
//            Item_ID_Field.setText(model.getValueAt(Myindex, 0).toString());
//            Item_Description_Field.setText(model.getValueAt(Myindex, 1).toString());
//            Total_In_Stock_Field.setText(model.getValueAt(Myindex, 2).toString());
//            Understock_Value_Field.setText(model.getValueAt(Myindex, 3).toString());
//            Sale_Price_Field.setText(model.getValueAt(Myindex, 4).toString());
//            Purchase_Price_Field.setText(model.getValueAt(Myindex, 5).toString());
//
//        } catch (SQLException ex) {
//            Logger.getLogger(ManagerWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        }
//        private ResultSet getData(Connection conn, String x ) throws SQLException{
//            ResultSet x1 = null;
//            String x2 = x;
//            String result = "abc";
//            PreparedStatement get = conn.prepareStatement("select Item_ID from Item_Information where Item_ID = ?;");
//            get.setString(1, x2);
//            x1 = get.executeQuery();
//            return x1;

    }//GEN-LAST:event_QTY_Report_DisplayMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Total_Sales_Month_DisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Total_Sales_Month_DisplayMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Total_Sales_Month_DisplayMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void Daily_QTY_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Daily_QTY_ReportActionPerformed
        // TODO add your handling code here:
        try{
            connect= DriverManager.getConnection(data_con, username, password);
            st = connect.createStatement();
            r_set= st.executeQuery("select * from Item_Information;");
            QTY_Report_Display.setModel(DbUtils.resultSetToTableModel(r_set));
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_Daily_QTY_ReportActionPerformed

    private void Daily_QTY_ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Daily_QTY_ReportMouseClicked
//        // TODO add your handling code here:
//        try {
//            connect = DriverManager.getConnection(data_con, username, password);
//            PreparedStatement in = connect.prepareStatement("insert into Item_Information values (?,?,?,?,?,?);");
//            in.setInt(1, Integer.valueOf(Item_ID_Field.getText()));
//            in.setString(2, Item_Description_Field.getText());
//            in.setInt(3, Integer.valueOf(Total_In_Stock_Field.getText()));
//            in.setFloat(4, Float.valueOf(Understock_Value_Field.getText()));
//            in.setFloat(5, Float.valueOf(Sale_Price_Field.getText()));
//            in.setFloat(6, Float.valueOf(Purchase_Price_Field.getText()));
//            in.executeUpdate();
//            JOptionPane.showMessageDialog(this, "Item Added Successfully");
//            Item_Info();
//        }
//        catch (Exception e){
//            e.printStackTrace();
//        }

    }//GEN-LAST:event_Daily_QTY_ReportMouseClicked

    private void Total_Sales_Month_EndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Total_Sales_Month_EndMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_Sales_Month_EndMouseClicked

    private void Total_Sales_Month_EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_Sales_Month_EndActionPerformed
        // TODO add your handling code here:
                try{
            connect= DriverManager.getConnection(data_con, username, password);
            st_Sales = connect.createStatement();
            r_set= st.executeQuery("select * from Sales_Information;");
            Total_Sales_Month_Display.setModel(DbUtils.resultSetToTableModel(r_set));
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_Total_Sales_Month_EndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Daily_QTY_Report;
    private javax.swing.JTable QTY_Report_Display;
    private javax.swing.JTable Total_Sales_Month_Display;
    private javax.swing.JButton Total_Sales_Month_End;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
