import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Daryl Branford
 */
public class ManagerWindow extends javax.swing.JFrame {
    private static final String username = "root";
  private static final String password = "root";
  private static final String data_con = "jdbc:mysql://localhost:3306/ZeroHardware";


    /**
     * Creates new form ManagerScreen
     */
    public ManagerWindow() {
        initComponents();
        setDefaultCloseOperation(ManagerWindow.DISPOSE_ON_CLOSE);
        Item_Info();
    }
    
    Connection connect = null;
        Statement statement = null;
        ResultSet r_set = null;
        
    public void Item_Info(){
        try{
            connect= DriverManager.getConnection(data_con, username, password);
            statement= connect.createStatement();
            r_set= statement.executeQuery("select * from Item_Information;");
            Item_Info_Display.setModel(DbUtils.resultSetToTableModel(r_set));
        }catch(Exception e){
            e.printStackTrace();
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Add_New_Item = new javax.swing.JButton();
        Increase_Q = new javax.swing.JButton();
        Remove_Item = new javax.swing.JButton();
        Modify_Item = new javax.swing.JButton();
        Produce_Reports = new javax.swing.JButton();
        Reset_Password = new javax.swing.JButton();
        Price_Check_Button = new javax.swing.JButton();
        Reset_Employee_Password = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Item_Info_Display = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Item_ID_Field = new javax.swing.JTextField();
        Item_Description_Field = new javax.swing.JTextField();
        Total_In_Stock_Field = new javax.swing.JTextField();
        Understock_Value_Field = new javax.swing.JTextField();
        Sale_Price_Field = new javax.swing.JTextField();
        Purchase_Price_Field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        Add_New_Item.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Add_New_Item.setText("Add New Item");
        Add_New_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_New_ItemMouseClicked(evt);
            }
        });
        Add_New_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_ItemActionPerformed(evt);
            }
        });

        Increase_Q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Increase_Q.setText("Increase Qty. of Item");
        Increase_Q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Increase_QMouseClicked(evt);
            }
        });
        Increase_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Increase_QActionPerformed(evt);
            }
        });

        Remove_Item.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Remove_Item.setText("Remove Item");
        Remove_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Remove_ItemMouseClicked(evt);
            }
        });
        Remove_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_ItemActionPerformed(evt);
            }
        });

        Modify_Item.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Modify_Item.setText("Modify Item");
        Modify_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Modify_ItemMouseClicked(evt);
            }
        });

        Produce_Reports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Produce_Reports.setText("Produce Reports");
        Produce_Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produce_ReportsActionPerformed(evt);
            }
        });

        Reset_Password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Reset_Password.setText("Reset Password");
        Reset_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_PasswordActionPerformed(evt);
            }
        });

        Price_Check_Button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Price_Check_Button.setText("Price Check");
        Price_Check_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price_Check_ButtonActionPerformed(evt);
            }
        });

        Reset_Employee_Password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Reset_Employee_Password.setText("Reset Employee Password");
        Reset_Employee_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_Employee_PasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Remove_Item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Increase_Q, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add_New_Item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Modify_Item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(3, 3, 3)))
                    .addComponent(Reset_Employee_Password)
                    .addComponent(Produce_Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Reset_Password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Price_Check_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Add_New_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Increase_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Remove_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Modify_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Produce_Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Price_Check_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Reset_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Reset_Employee_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("Manager's Menu");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Item_Info_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item Id", "Item Description", "Total in Stock", "Understock Value", "Sale Price", "Purchase Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Item_Info_Display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_Info_DisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Item_Info_Display);

        jLabel1.setText("Item ID");

        jLabel2.setText("Item Description");

        jLabel3.setText("Total in Stock");

        jLabel4.setText("Understock Value");

        jLabel5.setText("Sale Price");

        jLabel6.setText("Purchase Price");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        Purchase_Price_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_Price_FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Item_ID_Field)
                    .addComponent(Item_Description_Field)
                    .addComponent(Total_In_Stock_Field)
                    .addComponent(Understock_Value_Field)
                    .addComponent(Sale_Price_Field)
                    .addComponent(Purchase_Price_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Item_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Item_Description_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Total_In_Stock_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Understock_Value_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sale_Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Purchase_Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel8.setBackground(new java.awt.Color(204, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Zero's Hardware ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Purchase_Price_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_Price_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Purchase_Price_FieldActionPerformed

    private void Add_New_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_New_ItemMouseClicked
        // TODO add your handling code here:
        try {
                    connect = DriverManager.getConnection(data_con, username, password);
                    PreparedStatement in = connect.prepareStatement("insert into Item_Information values (?,?,?,?,?,?);");
                    in.setInt(1, Integer.valueOf(Item_ID_Field.getText()));
                    in.setString(2, Item_Description_Field.getText());
                    in.setInt(3, Integer.valueOf(Total_In_Stock_Field.getText()));
                    in.setFloat(4, Float.valueOf(Understock_Value_Field.getText()));
                    in.setFloat(5, Float.valueOf(Sale_Price_Field.getText()));
                    in.setFloat(6, Float.valueOf(Purchase_Price_Field.getText()));
                    in.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Item Added Successfully");
                    Item_Info();
                }
                catch (Exception e){
                    e.printStackTrace();
                }
    
    }//GEN-LAST:event_Add_New_ItemMouseClicked

    private void Modify_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modify_ItemMouseClicked
        // TODO add your handling code here:
        try {
            connect = DriverManager.getConnection(data_con, username, password);
            String Upd_Q = "update Item_Information set Item_ID='"+Item_ID_Field.getText()+"'"+","
                    + "Total_in_Stock='"+Total_In_Stock_Field.getText()+"'"+","
                    +"Sale_Price='"+Sale_Price_Field.getText()+"'"+", "
                    + "Purchase_Price= '"+Purchase_Price_Field.getText()+"'"+", Item_Description= '"+Item_Description_Field.getText()+"'"+" "
                    + "where Item_ID ="+Item_ID_Field.getText();
            statement = connect.createStatement();
            statement.executeUpdate(Upd_Q);
            JOptionPane.showMessageDialog(this, "Item Modified Successfully");
            Item_Info();
            
            

        } catch (SQLException ex) {
            Logger.getLogger(ManagerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Modify_ItemMouseClicked

    private void Remove_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Remove_ItemMouseClicked
        // TODO add your handling code here:
        try{
            connect = DriverManager.getConnection(data_con, username, password);
            String Remove ="Delete from Item_Information where Item_Id = " + Item_ID_Field.getText();
            statement = connect.createStatement();
            statement.executeUpdate(Remove);
            JOptionPane.showMessageDialog(this, "Item Removed Successfully");
            Item_Info();
            
        } catch (SQLException ex) {
            Logger.getLogger(ManagerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Remove_ItemMouseClicked

    private void Increase_QMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Increase_QMouseClicked
        // TODO add your handling code here:
//        try{
//            connect = DriverManager.getConnection(data_con, username, password);
//            String Increase ="Update Item_Information set Total_in_Stock= '"+
//                    "where Item_Id ="+Item_ID_Field.getText();
//            statement =connect.createStatement();
//            statement.executeUpdate(Increase);
//            JOptionPane.showMessageDialog(this, "Total in Stock Increased Successfully");
//            Item_Info();
//                 
//        } catch (SQLException ex) {
//            Logger.getLogger(ManagerWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_Increase_QMouseClicked

    private void Add_New_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_ItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_New_ItemActionPerformed

    private void Item_Info_DisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_Info_DisplayMouseClicked
        // TODO add your handling code here:
                                          
       DefaultTableModel model = (DefaultTableModel) Item_Info_Display.getModel();
       int Myindex = Item_Info_Display.getSelectedRow();
        try {
            getData(connect, "");
            Item_ID_Field.setText(model.getValueAt(Myindex, 0).toString());
            Item_Description_Field.setText(model.getValueAt(Myindex, 1).toString());
            Total_In_Stock_Field.setText(model.getValueAt(Myindex, 2).toString());
            Understock_Value_Field.setText(model.getValueAt(Myindex, 3).toString());
            Sale_Price_Field.setText(model.getValueAt(Myindex, 4).toString());
            Purchase_Price_Field.setText(model.getValueAt(Myindex, 5).toString());
            
        } catch (SQLException ex) {
            Logger.getLogger(ManagerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }                                              
    }
    private ResultSet getData(Connection conn, String x ) throws SQLException{
        ResultSet x1 = null;
        String x2 = x;
        String result = "abc";
        PreparedStatement get = conn.prepareStatement("select Item_ID from Item_Information where Item_ID = ?;");
        get.setString(1, x2);
        x1 = get.executeQuery();
        return x1;
       
    }//GEN-LAST:event_Item_Info_DisplayMouseClicked

    private void Reset_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_PasswordActionPerformed
        // TODO add your handling code here:
        new ResetPasswordManager().setVisible(true);
    }//GEN-LAST:event_Reset_PasswordActionPerformed

    private void Reset_Employee_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_Employee_PasswordActionPerformed
        // TODO add your handling code here:
        new ResetEmployeePassword().setVisible(true);
    }//GEN-LAST:event_Reset_Employee_PasswordActionPerformed

    private void Produce_ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produce_ReportsActionPerformed
        // TODO add your handling code here:
        ManagerReports mainMenu = new ManagerReports();
                        mainMenu.setVisible(true);
    }//GEN-LAST:event_Produce_ReportsActionPerformed

    private void Increase_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Increase_QActionPerformed
        // TODO add your handling code here:
        try{
            connect = DriverManager.getConnection(data_con, username, password);
            String Increase ="Update Item_Information set Total_in_Stock= '"+ Integer.valueOf(Total_In_Stock_Field.getText())+"'"+
                    "where Item_ID ="+Item_ID_Field.getText();
            statement =connect.createStatement();
            statement.executeUpdate(Increase);
            JOptionPane.showMessageDialog(this, "Total in Stock Increased Successfully");
            Item_Info();
                 
        } catch (SQLException ex) {
            Logger.getLogger(ManagerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Increase_QActionPerformed

    private void Price_Check_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price_Check_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price_Check_ButtonActionPerformed

    private void Remove_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_ItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Remove_ItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Item;
    private javax.swing.JButton Increase_Q;
    private javax.swing.JTextField Item_Description_Field;
    private javax.swing.JTextField Item_ID_Field;
    private javax.swing.JTable Item_Info_Display;
    private javax.swing.JButton Modify_Item;
    private javax.swing.JButton Price_Check_Button;
    private javax.swing.JButton Produce_Reports;
    private javax.swing.JTextField Purchase_Price_Field;
    private javax.swing.JButton Remove_Item;
    private javax.swing.JButton Reset_Employee_Password;
    private javax.swing.JButton Reset_Password;
    private javax.swing.JTextField Sale_Price_Field;
    private javax.swing.JTextField Total_In_Stock_Field;
    private javax.swing.JTextField Understock_Value_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
